package com.ceedpods.crmbuild.dto.product;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

/**
 * Response DTO for Get All Products API.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonPropertyOrder({"productId", "productName", "createdBy", "inDeals", "totalSales", "revenue"})
@Schema(description = "Product list response")
public class ProductListResponse {

    @Schema(description = "Unique identifier for the product", example = "product-01")
    private String productId;

    @Schema(description = "Name of the product", example = "Sales Training Program")
    private String productName;

    @Schema(description = "Information about the user who created the product")
    private CreatedBy createdBy;

    @Schema(description = "Number of deals that include this product", example = "15")
    private Long inDeals;

    @Schema(description = "Total number of sales of the product", example = "42")
    private Long totalSales;

    @Schema(description = "Total revenue generated by the product", example = "28500.00")
    private BigDecimal revenue;

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "User who created the product")
    public static class CreatedBy {

        @Schema(description = "ID of the user", example = "user-123")
        private String userId;

        @Schema(description = "Full name of the user", example = "John Doe")
        private String name;

        @Schema(description = "URL to the user's profile picture", example = "https://example.com/images/john.jpg")
        private String profilePicture;
    }
}
